// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddTodoHandlerFunc turns a function with the right signature into a add todo handler
type AddTodoHandlerFunc func(AddTodoParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddTodoHandlerFunc) Handle(params AddTodoParams) middleware.Responder {
	return fn(params)
}

// AddTodoHandler interface for that can handle valid add todo params
type AddTodoHandler interface {
	Handle(AddTodoParams) middleware.Responder
}

// NewAddTodo creates a new http.Handler for the add todo operation
func NewAddTodo(ctx *middleware.Context, handler AddTodoHandler) *AddTodo {
	return &AddTodo{Context: ctx, Handler: handler}
}

/*AddTodo swagger:route POST /todos todos addTodo

AddTodo add todo API

*/
type AddTodo struct {
	Context *middleware.Context
	Handler AddTodoHandler
}

func (o *AddTodo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddTodoParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
