// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "go-swagger-sample/models"
)

// AddTodoCreatedCode is the HTTP code returned for type AddTodoCreated
const AddTodoCreatedCode int = 201

/*AddTodoCreated Created

swagger:response addTodoCreated
*/
type AddTodoCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Item `json:"body,omitempty"`
}

// NewAddTodoCreated creates AddTodoCreated with default headers values
func NewAddTodoCreated() *AddTodoCreated {

	return &AddTodoCreated{}
}

// WithPayload adds the payload to the add todo created response
func (o *AddTodoCreated) WithPayload(payload *models.Item) *AddTodoCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add todo created response
func (o *AddTodoCreated) SetPayload(payload *models.Item) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddTodoCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AddTodoDefault error

swagger:response addTodoDefault
*/
type AddTodoDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddTodoDefault creates AddTodoDefault with default headers values
func NewAddTodoDefault(code int) *AddTodoDefault {
	if code <= 0 {
		code = 500
	}

	return &AddTodoDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add todo default response
func (o *AddTodoDefault) WithStatusCode(code int) *AddTodoDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add todo default response
func (o *AddTodoDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add todo default response
func (o *AddTodoDefault) WithPayload(payload *models.Error) *AddTodoDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add todo default response
func (o *AddTodoDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddTodoDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
