// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetTodoHandlerFunc turns a function with the right signature into a get todo handler
type GetTodoHandlerFunc func(GetTodoParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTodoHandlerFunc) Handle(params GetTodoParams) middleware.Responder {
	return fn(params)
}

// GetTodoHandler interface for that can handle valid get todo params
type GetTodoHandler interface {
	Handle(GetTodoParams) middleware.Responder
}

// NewGetTodo creates a new http.Handler for the get todo operation
func NewGetTodo(ctx *middleware.Context, handler GetTodoHandler) *GetTodo {
	return &GetTodo{Context: ctx, Handler: handler}
}

/*GetTodo swagger:route GET /todos/{id} todos getTodo

GetTodo get todo API

*/
type GetTodo struct {
	Context *middleware.Context
	Handler GetTodoHandler
}

func (o *GetTodo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTodoParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
